### ISSUE TITLE
error: "bad_state"

### ISSUE THREAD

**Issue by luskbo** [AngellusMortis/django_microsoft_auth#141]
* Django Microsoft Authentication Backend version: django-microsoft-auth-1.1.1 oauthlib-2.1.0 requests-oauthlib-1.0.0
* Python version: Python 3.5.3 (default, Jan 19 2017, 14:11:04)
* Operating System: 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 GNU/Linux

### Description

Followed instructions for install. 
Redirect failing with error.

```
Object { error_description: "An invalid state variable was provided. Please refresh the page and try again later.", error: "bad_state" }
```

### What I Did

Followed instructions for install. 
Initially, I didn't have sites framework installed. So installed:

Add 'django.contrib.sites' to your INSTALLED_APPS setting.
Define a SITE_ID setting:
SITE_ID = 1

/admin/sites/site/1/change/ if you have the admin site enabled.

Also, noticed after doing this, the incorrect URL was appearing in the  'authorization_url': 

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=cf28bef5-aa4d-41ac-89be-dc5c06f959e1&redirect_uri=https%3A%2F%2Fexample.com%2Fmicrosoft%2Fauth-callback%2F&scope=User.Read&state=cqHo4wstRvs8L2UiEN3F7NUGnpE0x29uzqTfPHBfP3THFW0Wwtiw05kw5mBJ6f6I&response_mode=form_post'});`

I followed steps here: [https://docs.djangoproject.com/en/1.11/ref/contrib/sites/#caching-the-current-site-object](https://docs.djangoproject.com/en/1.11/ref/contrib/sites/#caching-the-current-site-object)

After restarting the app, this resolved the issue.
URL was correct after restart.

Followed steps here:
8. Start site and goto /admin to and logout if you are logged in.
9. Login as Microsoft/Office 365/Xbox Live user. It will fail. This will automatically create your new user.

Login did fail, but a user was never created. 
I continued on with step 10 and logged in with a password user (superuser).
( This is where I noticed that user had not been created). 
I manually added 0365 user under "Microsoft accounts". 
Logged out of admin after this.

I then attempted to login:
Getting this error when trying to login with "Microsoft" button.
Pop-up box appears for MS authentication.
Login to O365 (with user added to admin).
Redirect takes place, to /microsoft/auth-callback/, in popup, but prints this message:
```
error: "bad_state"
error_description: "An invalid state variable was provided. Please refresh the page and try again later."
```
Then popup closes immediately.
Text is added to login box:
![capture](https://user-images.githubusercontent.com/3824412/48860638-11373a00-ed87-11e8-887a-3a09a642cbfd.PNG)

Looking at daphne logs, I can see the request taking place for the redirect.

` "POST /microsoft/auth-callback/ HTTP/1.1" 400 665 "https://login.microsoftonline.com/common/reprocess?ctx=rQIIAdNiNtIzsFJJTjO..........." "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
`

Any ideas?

**Comment by luskbo** [comment]
Another note:
I opened the authorization_url in a new browser window:

This is the response that I received after logging in:

`<html>
  <body>
    <p>This window should automatically close. If it does not, it should be save to close after a few seconds.</p>
    <pre>{"error_description": "An invalid state variable was provided. Please refresh the page and try again later.", "error": "bad_state"}</pre>
    <script>
      document.addEventListener("DOMContentLoaded", function(event) {
        // post message to parent window
        window.opener.postMessage({"error_description": "An invalid state variable was provided. Please refresh the page and try again later.", "error": "bad_state"}, "https://correctdomain.com/");
        window.close();
      });
    </script>
  </body>
</html>
`

https://correctdomain.com/ is the correct domain, although the name is fake for the example.

**Comment by luskbo** [comment]
Another Note:

Looking at microsoft_auth/views.py
I see that the only function that created the "bad_state" context is:
```

def _check_csrf(self, state):
        # validate state parameter
        if state is None or \
          not re.search('[a-zA-Z0-9]', state) or \
          not len(state) == CSRF_TOKEN_LENGTH or \
          not _compare_salted_tokens(state, get_token(self.request)):
            self.context['message'] = {'error': 'bad_state'}
```

Note sure where to go from here.......

**Comment by AngellusMortis** [comment]
Can you try clearing your cookies, session, restarting your browser, etc.? I am using all of the built in Django code for CSRF validation to implement the state checking.

**Comment by luskbo** [comment]
Thanks for the reply. 
Done that several times during troubleshooting.. 
I think it goes a bit deeper than that though unfortunately. 

Full disclosure, using nginx / daphne / django channels

I was watching the Django worker log while trying the authenticate. 

I see this hit the django runworker log:
```
2018-11-23 17:23:54,920 - DEBUG - worker - Dispatching message on http.request to channels.handler.ViewConsumer
Bad Request: /microsoft/auth-callback/
```

While this hits the daphne log:
```
2018-11-23 17:23:54,920 INFO     "127.0.0.1" - - [23/Nov/2018:17:26:28 +0000] "POST /microsoft/auth-callback/ HTTP/1.1" 400 665 "https://login.microsoftonline.com/common/reprocess?ctx=****&sessionid=*******" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
```

That is where it dies. 
However, while watching the django runworker log, I restarted the django worker.
While shutting down the workers, I see this appear in the logs:

```
2018-11-23 17:30:26,746 - INFO - worker - Shutdown signal received while idle, terminating immediately
{'state': '****', 'session_state': '***'}
```

This is the print statement from you function:

```
 def get_context_data(self, **kwargs):
        print(kwargs)
```

I added a test print statement after you print(kwargs).
This time, when restarting the worker after failing login, I can also see my test message print.

I'm not sure if the view function is just not getting called correctly, but also don't understand why I don't see the print(kwargs) output until I attempted to shut down the runworker.

I tried this several times in a row, by failing to login, clearing cache, and failing again. 
This time, when I restart the worker, I see a print for everytime tried to fail the login.

No idea what is going on here....

**Comment by AngellusMortis** [comment]
Sorry it took me so long to respond.

I believe I figured out what the issue is. It seems the CSRF validation completely breaks if you are using HTTP or your HTTPS is not configured correctly. Please try 1.2.0 as I added some improvements to help with using `DEBUG` and local development/testing. If it is still not working for you, please post your nginx configure so I can see how your reverse proxy and HTTPS is configured.

**Comment by newgamer1117** [comment]
hi threre :
    We got the same issue since we try to create a new Django project to adopt it.
But even we've followed the doc to set up, still no luck.
Always get "bad state" as the screenshot that luskbo provided previous.
Can you give us any advice please ?
Thanks.

**Comment by AngellusMortis** [comment]
Are you using version 1.2.0? Are you getting any check failures when you start up the Django app? The only thing I have seen that causes the CSRF/state validation to fail is is you are using HTTP and not HTTPS. With in depth knowledge of how your app is setup, all I can do is point you to the [Django docs on CSRF](https://docs.djangoproject.com/en/2.1/ref/csrf/)
